submissions_per_period: 5                                   # whatever number you want
log_worksheet_uuid: '0x70c99f30256f4de69ae64bcf3074633b'
submission_tag: super-unique-competition-submit             # come up with a unique tag

predict:
  mimic:
  - {new: '0x9b2ecd204ee34fdaa4f3555dbfc9e611', old: '0xa473153925d04b5d99ccc30c8a0be933'}  # test set replaces dev set
evaluate:
  dependencies:
  - {child_path: evaluate.py, parent_uuid: '0xc7e110ff84694cd79cabdd96fcc9a955'}
  - {child_path: test_set_answers.json, parent_uuid: '0x2402a3e8d9314f3d89580bdbadca4a08'}
  - {child_path: predictions.json, parent_path: 'predictions.json',  parent_uuid: '{predict}'}
  command: python3 evaluate.py test_set_answers.json predictions.json

score_specs:
- {key: '/stdout:MSE', name: MSE}
